// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lnlaisibniyojsuewxfc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxubGFpc2libml5b2pzdWV3eGZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1MDIxNDAsImV4cCI6MjA2MjA3ODE0MH0.cbxKKLzhts7mix-MfhHYbvulEDM0mjmRF94CawV52gw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);