
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lnlaisibniyojsuewxfc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxubGFpc2libml5b2pzdWV3eGZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1MDIxNDAsImV4cCI6MjA2MjA3ODE0MH0.cbxKKLzhts7mix-MfhHYbvulEDM0mjmRF94CawV52gw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Define custom types for our tables while waiting for the generated types to update
type CustomDatabase = {
  public: {
    Tables: {
      shipments: {
        Row: {
          id: string;
          shipment_id: string;
          destination: string;
          product: string;
          target_temperature: number;
          current_temperature: number | null;
          departure_date: string;
          estimated_arrival: string | null;
          status: string;
          user_id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          shipment_id: string;
          destination: string;
          product: string;
          target_temperature: number;
          current_temperature?: number | null;
          departure_date: string;
          estimated_arrival?: string | null;
          status: string;
          user_id: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          shipment_id?: string;
          destination?: string;
          product?: string;
          target_temperature?: number;
          current_temperature?: number | null;
          departure_date?: string;
          estimated_arrival?: string | null;
          status?: string;
          user_id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      temperature_logs: {
        Row: {
          id: string;
          shipment_id: string;
          temperature: number;
          is_alert: boolean | null;
          device_id: string | null;
          location: string | null;
          recorded_at: string;
        };
        Insert: {
          id?: string;
          shipment_id: string;
          temperature: number;
          is_alert?: boolean | null;
          device_id?: string | null;
          location?: string | null;
          recorded_at?: string;
        };
        Update: {
          id?: string;
          shipment_id?: string;
          temperature?: number;
          is_alert?: boolean | null;
          device_id?: string | null;
          location?: string | null;
          recorded_at?: string;
        };
      };
    };
  };
};

export const supabase = createClient<CustomDatabase>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
